apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2024-10-05T06:54:56Z"
  labels:
    kubernetes.io/metadata.name: ns-1
  name: ns-1
  resourceVersion: "837478"
  uid: 633d1cf9-6afa-42dc-90ec-cab4023139c9
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
