apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""] #"" indicates the core API group ex: apiVersion: v1
  resources: ["pods"]
  verbs: ["get", "watch", "list"]