apiVersion: v1
kind: Pod
metadata:
  name: mypod-2
  labels:
    name: mypod    
spec:
  containers:
  - name: mypod
    image: nginx
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    envFrom:
    - configMapRef:
        name: app-cm
    ports:
      - containerPort: 5001
