apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded value of 'username'
  password: cGFzc3dvcmQ=  # base64 encoded value of 'password'