apiVersion: v1 
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mycontainer
    image: busybox:1.28
    command: ['sh', '-c', 'echo "Hello, Kubernetes!"; sleep 3600']
    env:
    - name: MYVAR
      value: "Hello World"
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c']
    args: ['until nslookup myservice.default.svc.cluster; do echo waiting for myservice; sleep 2; done;']
